"""empty message

Revision ID: 397b859d69d9
Revises: 5500f8c8d75a
Create Date: 2023-01-05 22:47:53.861705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397b859d69d9'
down_revision = '5500f8c8d75a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('device_ip', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
