"""empty message

Revision ID: 5500f8c8d75a
Revises: 9ef66d0fb7d4
Create Date: 2023-01-05 18:30:46.815682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5500f8c8d75a'
down_revision = '9ef66d0fb7d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
